spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=identity_service
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signerKey: "d235efe323781650a6dd0d89a673bb98e6733aba4d84d60b0f022dfbb711b0fb"